/**
 * lakes-seed.js — Initial Minnesota lakes catalog.
 *
 * Coordinates are the generally-accepted lake-center points; admins can
 * refine them from the map view. Seed is idempotent (ON CONFLICT (slug)
 * DO NOTHING) so running it repeatedly never clobbers admin edits.
 *
 * Add new lakes by appending to this array and redeploying.
 */

module.exports = [
    {
        slug: 'lake-minnetonka',
        name: 'Lake Minnetonka',
        state: 'MN',
        region: 'Twin Cities Metro',
        county: 'Hennepin',
        latitude: 44.9083,
        longitude: -93.5853,
        intro_text: "Discover the pinnacle of Minnesota luxury. Unmatched waterfront estates, private yacht clubs, and elite dining — just 30 minutes from the Twin Cities.",
        description: "Lake Minnetonka isn't just a body of water — it's Minnesota's premier social and recreational playground. 14,528 acres of waterfront living stretch across Wayzata, Orono, Excelsior, and Minnetonka Beach, with a sprawling network of deep-water access, private docks, and transient slips at local institutions like Lord Fletcher's.\n\nOwn a lake home here and you get front-row VIP access to spectacular 4th of July fireworks, quiet morning paddle-boarding coves, and world-class walleye fishing 30 feet from your back patio. From historic generational estates overlooking Gray's Bay to ultra-modern glass marvels along Orono's shoreline, Lake Minnetonka's housing inventory represents the pinnacle of Midwestern architecture.",
        hero_image_url: '/assets/images/mn-winter-birch-chalet.jpg',
        featured_image_url: '/assets/images/mn-aerial-small-town.jpg',
        seo_title: 'Lake Minnetonka Homes for Sale | Luxury Waterfront Real Estate',
        seo_description: 'Browse luxury lake homes on Lake Minnetonka. Wayzata, Orono, Excelsior & Minnetonka Beach estates — private docks, elite schools, 30 minutes from the Twin Cities.',
        status: 'published',
    },
    {
        slug: 'gull-lake',
        name: 'Gull Lake',
        state: 'MN',
        region: 'Brainerd Lakes',
        county: 'Cass',
        latitude: 46.4097,
        longitude: -94.3483,
        intro_text: 'One of central Minnesota’s most sought-after resort lakes — 9,947 acres of clear water, sandy beaches, and top-rated golf just north of Brainerd.',
        seo_title: 'Gull Lake Homes for Sale | Brainerd Lakes Waterfront',
        seo_description: 'Gull Lake homes for sale in the Brainerd Lakes area. Sandy beaches, clear water, nationally-ranked golf, and cabin-country living.',
        status: 'published',
    },
    {
        slug: 'leech-lake',
        name: 'Leech Lake',
        state: 'MN',
        region: 'Northern Lakes',
        county: 'Cass',
        latitude: 47.1569,
        longitude: -94.3875,
        intro_text: 'Minnesota’s third-largest lake — 112,000 acres of legendary walleye fishing, Chippewa National Forest shoreline, and quiet cabin country.',
        seo_title: 'Leech Lake Homes for Sale | Walker, MN Waterfront Real Estate',
        seo_description: 'Leech Lake real estate near Walker, MN. Walleye fishing, Chippewa National Forest, and a slower pace of cabin life.',
        status: 'published',
    },
    {
        slug: 'mille-lacs-lake',
        name: 'Mille Lacs Lake',
        state: 'MN',
        region: 'Central Lakes',
        county: 'Mille Lacs',
        latitude: 46.2500,
        longitude: -93.6500,
        intro_text: 'Minnesota’s second-largest inland lake — 132,000 acres famed for world-class walleye, year-round fishing, and easy access from the Twin Cities.',
        seo_title: 'Mille Lacs Lake Homes for Sale | Walleye Capital Real Estate',
        seo_description: 'Mille Lacs Lake real estate — waterfront homes and cabins on Minnesota’s walleye capital, two hours north of Minneapolis.',
        status: 'published',
    },
    {
        slug: 'lake-vermilion',
        name: 'Lake Vermilion',
        state: 'MN',
        region: 'Iron Range / Arrowhead',
        county: 'St. Louis',
        latitude: 47.8833,
        longitude: -92.3500,
        intro_text: 'A 40,000-acre wilderness lake at the edge of the Boundary Waters — 365 islands, rocky shoreline, and some of Minnesota’s most iconic cabin country.',
        seo_title: 'Lake Vermilion Homes for Sale | Northern Minnesota Wilderness Lake',
        seo_description: 'Lake Vermilion real estate in Minnesota’s Arrowhead region. Island cabins, granite shoreline, and Boundary Waters adjacency.',
        status: 'published',
    },
    {
        slug: 'lake-of-the-woods',
        name: 'Lake of the Woods',
        state: 'MN',
        region: 'Border Waters',
        county: 'Lake of the Woods',
        latitude: 49.1000,
        longitude: -94.8000,
        intro_text: 'Minnesota’s northernmost destination lake — 950,000 acres straddling the Canadian border, legendary for walleye, sauger, and remote island retreats.',
        seo_title: 'Lake of the Woods Homes for Sale | Baudette, MN Real Estate',
        seo_description: 'Lake of the Woods real estate — waterfront cabins, resorts, and island properties on the Canadian border.',
        status: 'published',
    },
    {
        slug: 'detroit-lake',
        name: 'Detroit Lake',
        state: 'MN',
        region: 'Lakes Country',
        county: 'Becker',
        latitude: 46.7866,
        longitude: -95.8456,
        intro_text: "A 3,000-acre walleye and muskie lake in northwest MN's lakes country — the kind of summer-cabin-on-the-water destination Minnesotans drive three hours for and Fargo families come to most weekends.",
        description: "Detroit Lake sits in Becker County, about 225 miles northwest of the Twin Cities — roughly three and a half hours via I-94 and Highway 10 — and an easy hour east of Fargo–Moorhead. The city of Detroit Lakes shares the lake's southwestern shore, which makes this one of the rare Minnesota lakes where you can walk from a coffee shop to a public beach in under five minutes.\n\nThe lake covers roughly 3,000 acres of surface water, with a maximum depth around 88 feet and an average depth near 32 feet. The main basin (Big Detroit) connects to Little Detroit Lake on the north end, and the wider Detroit Lakes chain — Big Cormorant, Lake Sallie, Lake Melissa, Floyd Lake, Long Lake — sits within an easy boat or short drive away. That chain is the structural reason buyers come to this market: a Detroit Lake address gives you fast access to a half-dozen distinct lakes without locking yourself into one shoreline.\n\nBuyers landing on Detroit Lake for the first time tend to come from one of three places. Fargo–Moorhead families looking for a weekend cabin within an hour. Twin Cities families looking for somewhere quieter than the Brainerd Lakes Area. And out-of-state retirees — Iowa, Texas, Arizona — who summer in Detroit Lakes and winter south. The result is a lake with the activity of a tourist town and the residential rhythm of a place that actually runs year-round. The city itself sits at about 9,500 people year-round and roughly doubles in summer.\n\nFor fishing, the signature game is walleye and muskie. Detroit Lake is on the Minnesota DNR's muskie-management list and has produced serious fish for decades. Northern pike, smallmouth and largemouth bass, and a strong panfish population (sunfish, crappies, perch) round out the lineup. Boating culture is mature — pontoons dominate the social side, but the main basin has enough room for water skiing while Little Detroit and the connecting channels stay quiet for paddlers and morning fishing.\n\nThe summer calendar is busy in a way that surprises first-timers. The Water Carnival in July, Polar Fest in February (ice fishing tournaments and a literal jump into a hole cut in the lake), and WE Fest, the country music festival at Soo Pass Ranch just outside town, draw tens of thousands of out-of-town visitors each year. Detroit Mountain Recreation Area on the south edge of town runs year-round — skiing and tubing in winter, mountain biking and disc golf in summer.\n\nThe town side gives the lake its commercial backbone, and it's better than most. Downtown is compact and walkable. The Pavilion is a historic lakeside landmark hosting concerts and events. Holmes Theatre handles arts programming, and a scattering of locally-owned restaurants and shops keep the place feeling like a real town rather than a strip-mall vacation outpost. Essentia Health St. Mary's hospital handles the medical side. Detroit Lakes Public Schools serves year-round families and is regarded well for a district of its size.\n\nDrive times worth knowing: Fargo–Moorhead is about an hour. Bemidji is about ninety minutes. Brainerd is about ninety minutes east. The Twin Cities is three and a half hours.\n\nDetroit Lake sits in the mid-tier of Minnesota lake-home pricing — less expensive than Lake Minnetonka or the Whitefish Chain, more developed and pricier than the dozens of smaller lakes scattered across Becker County. Inventory typically falls into three bands: vintage cabins from roughly $400K to $700K, mid-tier modern lake homes between $700K and $1.5M, and a smaller cluster of luxury estates above $2M. Lot character — proximity to town, depth of the parcel, dock access — drives price more than home square footage on this lake.\n\nSeasonality follows the standard Minnesota pattern. Inventory peaks in late spring as sellers prep for summer showings; the most competitive bidding happens between Memorial Day and the Fourth of July. Most listings come off by Labor Day, and winter inventory is thinner and skews toward pre-arranged off-market deals through local agents.",
        hero_image_url: '/assets/images/mn-aerial-small-town.jpg',
        featured_image_url: '/assets/images/mn-couple-lake-sunset.jpg',
        seo_title: 'Detroit Lake Homes for Sale | MN Lake Homes',
        seo_description: 'Browse homes on Detroit Lake in Detroit Lakes, MN. Lake-home market data, trusted local agents, and a curated list of resorts, marinas, and lake-area pros.',
        status: 'published',
    },
    {
        slug: 'pelican-lake',
        name: 'Pelican Lake',
        state: 'MN',
        region: 'Lakes Country',
        county: 'Otter Tail',
        latitude: 46.5667,
        longitude: -95.9167,
        intro_text: 'An 11,000-acre gem in Otter Tail County — clear water, sandy bottom, and some of west-central Minnesota’s most desirable lakefront.',
        seo_title: 'Pelican Lake Homes for Sale | Otter Tail County Waterfront',
        seo_description: 'Pelican Lake real estate in Otter Tail County, MN. Clear water, sandy beaches, and classic west-central Minnesota cabin country.',
        status: 'published',
    },
    {
        slug: 'cass-lake',
        name: 'Cass Lake',
        state: 'MN',
        region: 'Northern Lakes',
        county: 'Cass',
        latitude: 47.3833,
        longitude: -94.6000,
        intro_text: '15,000-acre lake inside the Chippewa National Forest — connected to the Mississippi River headwaters and known for musky, walleye, and old-growth pines.',
        seo_title: 'Cass Lake Homes for Sale | Chippewa National Forest Waterfront',
        seo_description: 'Cass Lake real estate in northern Minnesota — Chippewa National Forest shoreline, Mississippi River connection, and deep-woods cabin living.',
        status: 'published',
    },
    {
        slug: 'white-bear-lake',
        name: 'White Bear Lake',
        state: 'MN',
        region: 'Twin Cities Metro',
        county: 'Ramsey',
        latitude: 45.0833,
        longitude: -93.0167,
        intro_text: 'A 2,400-acre east-metro lake ringed by classic bungalows and newer estates — 20 minutes from downtown St. Paul, with a walkable Main Street and year-round boating.',
        seo_title: 'White Bear Lake Homes for Sale | East Metro Waterfront',
        seo_description: 'White Bear Lake real estate in the east Twin Cities metro. Historic Main Street, year-round lake life, and 20 minutes from downtown St. Paul.',
        status: 'published',
    },
];
