/**
 * lakes-seed.js — Initial Minnesota lakes catalog.
 *
 * Coordinates are the generally-accepted lake-center points; admins can
 * refine them from the map view. Seed is idempotent (ON CONFLICT (slug)
 * DO NOTHING) so running it repeatedly never clobbers admin edits.
 *
 * Add new lakes by appending to this array and redeploying.
 */

module.exports = [
    {
        slug: 'lake-minnetonka',
        name: 'Lake Minnetonka',
        state: 'MN',
        region: 'Twin Cities Metro',
        county: 'Hennepin',
        latitude: 44.9083,
        longitude: -93.5853,
        intro_text: "Minnesota's premier luxury lake — 14,528 acres of waterfront living across Wayzata, Orono, Excelsior, and Minnetonka Beach.",
        seo_title: 'Lake Minnetonka Homes for Sale | Luxury Waterfront Real Estate',
        seo_description: 'Browse luxury lake homes on Lake Minnetonka. Wayzata, Orono, Excelsior & Minnetonka Beach estates — private docks, elite schools, 30 minutes from the Twin Cities.',
        status: 'published',
    },
    {
        slug: 'gull-lake',
        name: 'Gull Lake',
        state: 'MN',
        region: 'Brainerd Lakes',
        county: 'Cass',
        latitude: 46.4097,
        longitude: -94.3483,
        intro_text: 'One of central Minnesota’s most sought-after resort lakes — 9,947 acres of clear water, sandy beaches, and top-rated golf just north of Brainerd.',
        seo_title: 'Gull Lake Homes for Sale | Brainerd Lakes Waterfront',
        seo_description: 'Gull Lake homes for sale in the Brainerd Lakes area. Sandy beaches, clear water, nationally-ranked golf, and cabin-country living.',
        status: 'published',
    },
    {
        slug: 'leech-lake',
        name: 'Leech Lake',
        state: 'MN',
        region: 'Northern Lakes',
        county: 'Cass',
        latitude: 47.1569,
        longitude: -94.3875,
        intro_text: 'Minnesota’s third-largest lake — 112,000 acres of legendary walleye fishing, Chippewa National Forest shoreline, and quiet cabin country.',
        seo_title: 'Leech Lake Homes for Sale | Walker, MN Waterfront Real Estate',
        seo_description: 'Leech Lake real estate near Walker, MN. Walleye fishing, Chippewa National Forest, and a slower pace of cabin life.',
        status: 'published',
    },
    {
        slug: 'mille-lacs-lake',
        name: 'Mille Lacs Lake',
        state: 'MN',
        region: 'Central Lakes',
        county: 'Mille Lacs',
        latitude: 46.2500,
        longitude: -93.6500,
        intro_text: 'Minnesota’s second-largest inland lake — 132,000 acres famed for world-class walleye, year-round fishing, and easy access from the Twin Cities.',
        seo_title: 'Mille Lacs Lake Homes for Sale | Walleye Capital Real Estate',
        seo_description: 'Mille Lacs Lake real estate — waterfront homes and cabins on Minnesota’s walleye capital, two hours north of Minneapolis.',
        status: 'published',
    },
    {
        slug: 'lake-vermilion',
        name: 'Lake Vermilion',
        state: 'MN',
        region: 'Iron Range / Arrowhead',
        county: 'St. Louis',
        latitude: 47.8833,
        longitude: -92.3500,
        intro_text: 'A 40,000-acre wilderness lake at the edge of the Boundary Waters — 365 islands, rocky shoreline, and some of Minnesota’s most iconic cabin country.',
        seo_title: 'Lake Vermilion Homes for Sale | Northern Minnesota Wilderness Lake',
        seo_description: 'Lake Vermilion real estate in Minnesota’s Arrowhead region. Island cabins, granite shoreline, and Boundary Waters adjacency.',
        status: 'published',
    },
    {
        slug: 'lake-of-the-woods',
        name: 'Lake of the Woods',
        state: 'MN',
        region: 'Border Waters',
        county: 'Lake of the Woods',
        latitude: 49.1000,
        longitude: -94.8000,
        intro_text: 'Minnesota’s northernmost destination lake — 950,000 acres straddling the Canadian border, legendary for walleye, sauger, and remote island retreats.',
        seo_title: 'Lake of the Woods Homes for Sale | Baudette, MN Real Estate',
        seo_description: 'Lake of the Woods real estate — waterfront cabins, resorts, and island properties on the Canadian border.',
        status: 'published',
    },
    {
        slug: 'detroit-lake',
        name: 'Detroit Lake',
        state: 'MN',
        region: 'Lakes Country',
        county: 'Becker',
        latitude: 46.8167,
        longitude: -95.8333,
        intro_text: '3,000-acre spring-fed lake anchoring downtown Detroit Lakes — family-friendly beaches, a classic Main Street, and a three-hour drive from the Twin Cities.',
        seo_title: 'Detroit Lake Homes for Sale | Detroit Lakes, MN Real Estate',
        seo_description: 'Detroit Lake real estate — waterfront homes, family cabins, and resort-style living in Minnesota’s Lakes Country.',
        status: 'published',
    },
    {
        slug: 'pelican-lake',
        name: 'Pelican Lake',
        state: 'MN',
        region: 'Lakes Country',
        county: 'Otter Tail',
        latitude: 46.5667,
        longitude: -95.9167,
        intro_text: 'An 11,000-acre gem in Otter Tail County — clear water, sandy bottom, and some of west-central Minnesota’s most desirable lakefront.',
        seo_title: 'Pelican Lake Homes for Sale | Otter Tail County Waterfront',
        seo_description: 'Pelican Lake real estate in Otter Tail County, MN. Clear water, sandy beaches, and classic west-central Minnesota cabin country.',
        status: 'published',
    },
    {
        slug: 'cass-lake',
        name: 'Cass Lake',
        state: 'MN',
        region: 'Northern Lakes',
        county: 'Cass',
        latitude: 47.3833,
        longitude: -94.6000,
        intro_text: '15,000-acre lake inside the Chippewa National Forest — connected to the Mississippi River headwaters and known for musky, walleye, and old-growth pines.',
        seo_title: 'Cass Lake Homes for Sale | Chippewa National Forest Waterfront',
        seo_description: 'Cass Lake real estate in northern Minnesota — Chippewa National Forest shoreline, Mississippi River connection, and deep-woods cabin living.',
        status: 'published',
    },
    {
        slug: 'white-bear-lake',
        name: 'White Bear Lake',
        state: 'MN',
        region: 'Twin Cities Metro',
        county: 'Ramsey',
        latitude: 45.0833,
        longitude: -93.0167,
        intro_text: 'A 2,400-acre east-metro lake ringed by classic bungalows and newer estates — 20 minutes from downtown St. Paul, with a walkable Main Street and year-round boating.',
        seo_title: 'White Bear Lake Homes for Sale | East Metro Waterfront',
        seo_description: 'White Bear Lake real estate in the east Twin Cities metro. Historic Main Street, year-round lake life, and 20 minutes from downtown St. Paul.',
        status: 'published',
    },
];
