/**
 * tags-seed.js — Geographic tags bootstrapped at app start.
 *
 * Run by src/server.js ensureTables() with an INSERT … ON CONFLICT (slug)
 * DO NOTHING so the list is safe to reload every boot. Coordinates are
 * approximate — refine via Google Geocoding if/when the admin hits
 * "verify coords" from the tags page.
 */

module.exports = [
    // ── Twin Cities Metro ────────────────────────────────────────────────────
    { slug: 'minneapolis',         name: 'Minneapolis',         state: 'MN', region: 'Twin Cities Metro', latitude: 44.9778, longitude: -93.2650 },
    { slug: 'saint-paul',          name: 'Saint Paul',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.9537, longitude: -93.0900 },
    { slug: 'bloomington',         name: 'Bloomington',         state: 'MN', region: 'Twin Cities Metro', latitude: 44.8408, longitude: -93.2983 },
    { slug: 'plymouth',            name: 'Plymouth',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.0105, longitude: -93.4555 },
    { slug: 'maple-grove',         name: 'Maple Grove',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.0725, longitude: -93.4557 },
    { slug: 'woodbury',            name: 'Woodbury',            state: 'MN', region: 'Twin Cities Metro', latitude: 44.9239, longitude: -92.9594 },
    { slug: 'eagan',               name: 'Eagan',               state: 'MN', region: 'Twin Cities Metro', latitude: 44.8041, longitude: -93.1669 },
    { slug: 'eden-prairie',        name: 'Eden Prairie',        state: 'MN', region: 'Twin Cities Metro', latitude: 44.8547, longitude: -93.4708 },
    { slug: 'coon-rapids',         name: 'Coon Rapids',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.1199, longitude: -93.2876 },
    { slug: 'burnsville',          name: 'Burnsville',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.7678, longitude: -93.2777 },
    { slug: 'minnetonka',          name: 'Minnetonka',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.9212, longitude: -93.4687 },
    { slug: 'apple-valley',        name: 'Apple Valley',        state: 'MN', region: 'Twin Cities Metro', latitude: 44.7319, longitude: -93.2177 },
    { slug: 'edina',               name: 'Edina',               state: 'MN', region: 'Twin Cities Metro', latitude: 44.8897, longitude: -93.3499 },
    { slug: 'lakeville',           name: 'Lakeville',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.6497, longitude: -93.2427 },
    { slug: 'blaine',              name: 'Blaine',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.1608, longitude: -93.2349 },
    { slug: 'brooklyn-park',       name: 'Brooklyn Park',       state: 'MN', region: 'Twin Cities Metro', latitude: 45.0941, longitude: -93.3563 },
    { slug: 'brooklyn-center',     name: 'Brooklyn Center',     state: 'MN', region: 'Twin Cities Metro', latitude: 45.0761, longitude: -93.3328 },
    { slug: 'champlin',            name: 'Champlin',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.1886, longitude: -93.3971 },
    { slug: 'chanhassen',          name: 'Chanhassen',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.8622, longitude: -93.5300 },
    { slug: 'chaska',              name: 'Chaska',              state: 'MN', region: 'Twin Cities Metro', latitude: 44.7894, longitude: -93.6024 },
    { slug: 'elk-river',           name: 'Elk River',           state: 'MN', region: 'Twin Cities Metro', latitude: 45.3038, longitude: -93.5671 },
    { slug: 'farmington',          name: 'Farmington',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.6402, longitude: -93.1435 },
    { slug: 'forest-lake',         name: 'Forest Lake',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.2791, longitude: -92.9852 },
    { slug: 'fridley',             name: 'Fridley',             state: 'MN', region: 'Twin Cities Metro', latitude: 45.0861, longitude: -93.2634 },
    { slug: 'golden-valley',       name: 'Golden Valley',       state: 'MN', region: 'Twin Cities Metro', latitude: 45.0025, longitude: -93.3497 },
    { slug: 'ham-lake',            name: 'Ham Lake',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.2502, longitude: -93.2499 },
    { slug: 'hastings',            name: 'Hastings',            state: 'MN', region: 'Twin Cities Metro', latitude: 44.7436, longitude: -92.8524 },
    { slug: 'hopkins',             name: 'Hopkins',             state: 'MN', region: 'Twin Cities Metro', latitude: 44.9252, longitude: -93.4625 },
    { slug: 'hugo',                name: 'Hugo',                state: 'MN', region: 'Twin Cities Metro', latitude: 45.1608, longitude: -92.9738 },
    { slug: 'mahtomedi',           name: 'Mahtomedi',           state: 'MN', region: 'Twin Cities Metro', latitude: 45.0691, longitude: -92.9508 },
    { slug: 'maplewood',           name: 'Maplewood',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9530, longitude: -92.9952 },
    { slug: 'mounds-view',         name: 'Mounds View',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.1047, longitude: -93.2080 },
    { slug: 'new-brighton',        name: 'New Brighton',        state: 'MN', region: 'Twin Cities Metro', latitude: 45.0655, longitude: -93.2019 },
    { slug: 'new-hope',            name: 'New Hope',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.0380, longitude: -93.3867 },
    { slug: 'oakdale',             name: 'Oakdale',             state: 'MN', region: 'Twin Cities Metro', latitude: 44.9630, longitude: -92.9649 },
    { slug: 'orono',               name: 'Orono',               state: 'MN', region: 'Twin Cities Metro', latitude: 44.9752, longitude: -93.6002 },
    { slug: 'prior-lake',          name: 'Prior Lake',          state: 'MN', region: 'Twin Cities Metro', latitude: 44.7133, longitude: -93.4225 },
    { slug: 'ramsey',              name: 'Ramsey',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.2611, longitude: -93.4499 },
    { slug: 'richfield',           name: 'Richfield',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.8833, longitude: -93.2830 },
    { slug: 'rogers',              name: 'Rogers',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.1886, longitude: -93.5533 },
    { slug: 'rosemount',           name: 'Rosemount',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.7394, longitude: -93.1266 },
    { slug: 'roseville',           name: 'Roseville',           state: 'MN', region: 'Twin Cities Metro', latitude: 45.0061, longitude: -93.1566 },
    { slug: 'savage',              name: 'Savage',              state: 'MN', region: 'Twin Cities Metro', latitude: 44.7792, longitude: -93.3363 },
    { slug: 'shakopee',            name: 'Shakopee',            state: 'MN', region: 'Twin Cities Metro', latitude: 44.7974, longitude: -93.5269 },
    { slug: 'shoreview',           name: 'Shoreview',           state: 'MN', region: 'Twin Cities Metro', latitude: 45.0793, longitude: -93.1469 },
    { slug: 'south-saint-paul',    name: 'South Saint Paul',    state: 'MN', region: 'Twin Cities Metro', latitude: 44.8928, longitude: -93.0349 },
    { slug: 'stillwater',          name: 'Stillwater',          state: 'MN', region: 'Twin Cities Metro', latitude: 45.0564, longitude: -92.8060 },
    { slug: 'st-louis-park',       name: 'St. Louis Park',      state: 'MN', region: 'Twin Cities Metro', latitude: 44.9483, longitude: -93.3480 },
    { slug: 'vadnais-heights',     name: 'Vadnais Heights',     state: 'MN', region: 'Twin Cities Metro', latitude: 45.0494, longitude: -93.0880 },
    { slug: 'west-saint-paul',     name: 'West Saint Paul',     state: 'MN', region: 'Twin Cities Metro', latitude: 44.9164, longitude: -93.0997 },
    { slug: 'white-bear-lake',     name: 'White Bear Lake',     state: 'MN', region: 'Twin Cities Metro', latitude: 45.0847, longitude: -93.0094 },
    { slug: 'wayzata',             name: 'Wayzata',             state: 'MN', region: 'Twin Cities Metro', latitude: 44.9733, longitude: -93.5066 },
    { slug: 'crystal',             name: 'Crystal',             state: 'MN', region: 'Twin Cities Metro', latitude: 45.0324, longitude: -93.3602 },
    { slug: 'robbinsdale',         name: 'Robbinsdale',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.0319, longitude: -93.3388 },
    { slug: 'anoka',               name: 'Anoka',               state: 'MN', region: 'Twin Cities Metro', latitude: 45.1977, longitude: -93.3872 },
    { slug: 'columbia-heights',    name: 'Columbia Heights',    state: 'MN', region: 'Twin Cities Metro', latitude: 45.0407, longitude: -93.2630 },
    { slug: 'andover',             name: 'Andover',             state: 'MN', region: 'Twin Cities Metro', latitude: 45.2330, longitude: -93.2913 },
    { slug: 'cottage-grove',       name: 'Cottage Grove',       state: 'MN', region: 'Twin Cities Metro', latitude: 44.8277, longitude: -92.9438 },
    { slug: 'inver-grove-heights', name: 'Inver Grove Heights', state: 'MN', region: 'Twin Cities Metro', latitude: 44.8480, longitude: -93.0427 },
    { slug: 'spring-lake-park',    name: 'Spring Lake Park',    state: 'MN', region: 'Twin Cities Metro', latitude: 45.1080, longitude: -93.2399 },
    { slug: 'arden-hills',         name: 'Arden Hills',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.0610, longitude: -93.1566 },
    { slug: 'little-canada',       name: 'Little Canada',       state: 'MN', region: 'Twin Cities Metro', latitude: 45.0258, longitude: -93.0871 },
    { slug: 'mendota-heights',     name: 'Mendota Heights',     state: 'MN', region: 'Twin Cities Metro', latitude: 44.8833, longitude: -93.1372 },
    { slug: 'north-saint-paul',    name: 'North Saint Paul',    state: 'MN', region: 'Twin Cities Metro', latitude: 45.0102, longitude: -92.9913 },
    { slug: 'excelsior',           name: 'Excelsior',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9030, longitude: -93.5663 },
    { slug: 'lino-lakes',          name: 'Lino Lakes',          state: 'MN', region: 'Twin Cities Metro', latitude: 45.1608, longitude: -93.0869 },
    { slug: 'minnetrista',         name: 'Minnetrista',         state: 'MN', region: 'Twin Cities Metro', latitude: 44.9158, longitude: -93.6588 },
    { slug: 'mound',               name: 'Mound',               state: 'MN', region: 'Twin Cities Metro', latitude: 44.9361, longitude: -93.6660 },
    { slug: 'spring-park',         name: 'Spring Park',         state: 'MN', region: 'Twin Cities Metro', latitude: 44.9358, longitude: -93.6302 },
    { slug: 'tonka-bay',           name: 'Tonka Bay',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9105, longitude: -93.5805 },
    { slug: 'shorewood',           name: 'Shorewood',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.8999, longitude: -93.5888 },
    { slug: 'deephaven',           name: 'Deephaven',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9261, longitude: -93.5291 },
    { slug: 'greenwood',           name: 'Greenwood',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9044, longitude: -93.5421 },
    { slug: 'minnetonka-beach',    name: 'Minnetonka Beach',    state: 'MN', region: 'Twin Cities Metro', latitude: 44.9386, longitude: -93.5961 },
    { slug: 'independence',        name: 'Independence',        state: 'MN', region: 'Twin Cities Metro', latitude: 45.0283, longitude: -93.7086 },
    { slug: 'medina',              name: 'Medina',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.0352, longitude: -93.5708 },
    { slug: 'maple-plain',         name: 'Maple Plain',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.0074, longitude: -93.6555 },
    { slug: 'long-lake',           name: 'Long Lake',           state: 'MN', region: 'Twin Cities Metro', latitude: 44.9844, longitude: -93.5697 },
    { slug: 'osseo',               name: 'Osseo',               state: 'MN', region: 'Twin Cities Metro', latitude: 45.1194, longitude: -93.4022 },
    { slug: 'dayton',              name: 'Dayton',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.2449, longitude: -93.5097 },
    { slug: 'corcoran',            name: 'Corcoran',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.0944, longitude: -93.5461 },
    { slug: 'albertville',         name: 'Albertville',         state: 'MN', region: 'Twin Cities Metro', latitude: 45.2377, longitude: -93.6547 },
    { slug: 'st-michael',          name: 'Saint Michael',       state: 'MN', region: 'Twin Cities Metro', latitude: 45.2083, longitude: -93.6647 },
    { slug: 'otsego',              name: 'Otsego',              state: 'MN', region: 'Twin Cities Metro', latitude: 45.2719, longitude: -93.6014 },
    { slug: 'monticello',          name: 'Monticello',          state: 'MN', region: 'Twin Cities Metro', latitude: 45.3055, longitude: -93.7941 },
    { slug: 'buffalo',             name: 'Buffalo',             state: 'MN', region: 'Twin Cities Metro', latitude: 45.1719, longitude: -93.8747 },
    { slug: 'big-lake',            name: 'Big Lake',            state: 'MN', region: 'Twin Cities Metro', latitude: 45.3327, longitude: -93.7480 },

    // ── Central MN ───────────────────────────────────────────────────────────
    { slug: 'becker',              name: 'Becker',              state: 'MN', region: 'Central MN', latitude: 45.3966, longitude: -93.8774 },
    { slug: 'clearwater',          name: 'Clearwater',          state: 'MN', region: 'Central MN', latitude: 45.4208, longitude: -94.0483 },
    { slug: 'st-cloud',            name: 'Saint Cloud',         state: 'MN', region: 'Central MN', latitude: 45.5579, longitude: -94.1632 },
    { slug: 'sartell',             name: 'Sartell',             state: 'MN', region: 'Central MN', latitude: 45.6219, longitude: -94.2070 },
    { slug: 'sauk-rapids',         name: 'Sauk Rapids',         state: 'MN', region: 'Central MN', latitude: 45.5908, longitude: -94.1669 },
    { slug: 'waite-park',          name: 'Waite Park',          state: 'MN', region: 'Central MN', latitude: 45.5563, longitude: -94.2236 },
    { slug: 'st-joseph',           name: 'Saint Joseph',        state: 'MN', region: 'Central MN', latitude: 45.5658, longitude: -94.3175 },
    { slug: 'avon',                name: 'Avon',                state: 'MN', region: 'Central MN', latitude: 45.6094, longitude: -94.4505 },
    { slug: 'albany',              name: 'Albany',              state: 'MN', region: 'Central MN', latitude: 45.6300, longitude: -94.5702 },
    { slug: 'melrose',             name: 'Melrose',             state: 'MN', region: 'Central MN', latitude: 45.6744, longitude: -94.8108 },
    { slug: 'sauk-centre',         name: 'Sauk Centre',         state: 'MN', region: 'Central MN', latitude: 45.7372, longitude: -94.9525 },
    { slug: 'little-falls',        name: 'Little Falls',        state: 'MN', region: 'Central MN', latitude: 45.9763, longitude: -94.3625 },

    // ── East Central MN ──────────────────────────────────────────────────────
    { slug: 'princeton',           name: 'Princeton',           state: 'MN', region: 'East Central MN', latitude: 45.5702, longitude: -93.5819 },
    { slug: 'milaca',              name: 'Milaca',              state: 'MN', region: 'East Central MN', latitude: 45.7561, longitude: -93.6525 },
    { slug: 'mora',                name: 'Mora',                state: 'MN', region: 'East Central MN', latitude: 45.8772, longitude: -93.2941 },
    { slug: 'cambridge',           name: 'Cambridge',           state: 'MN', region: 'East Central MN', latitude: 45.5725, longitude: -93.2244 },
    { slug: 'isanti',              name: 'Isanti',              state: 'MN', region: 'East Central MN', latitude: 45.4911, longitude: -93.2469 },
    { slug: 'pine-city',           name: 'Pine City',           state: 'MN', region: 'East Central MN', latitude: 45.8258, longitude: -92.9685 },
    { slug: 'hinckley',            name: 'Hinckley',            state: 'MN', region: 'East Central MN', latitude: 46.0119, longitude: -92.9444 },
    { slug: 'sandstone',           name: 'Sandstone',           state: 'MN', region: 'East Central MN', latitude: 46.1322, longitude: -92.8680 },
    { slug: 'north-branch',        name: 'North Branch',        state: 'MN', region: 'East Central MN', latitude: 45.5111, longitude: -92.9802 },

    // ── Brainerd Lakes ───────────────────────────────────────────────────────
    { slug: 'brainerd',            name: 'Brainerd',            state: 'MN', region: 'Brainerd Lakes', latitude: 46.3580, longitude: -94.2008 },
    { slug: 'baxter',              name: 'Baxter',              state: 'MN', region: 'Brainerd Lakes', latitude: 46.3430, longitude: -94.2869 },
    { slug: 'nisswa',              name: 'Nisswa',              state: 'MN', region: 'Brainerd Lakes', latitude: 46.5205, longitude: -94.2886 },
    { slug: 'pequot-lakes',        name: 'Pequot Lakes',        state: 'MN', region: 'Brainerd Lakes', latitude: 46.6038, longitude: -94.3083 },
    { slug: 'crosslake',           name: 'Crosslake',           state: 'MN', region: 'Brainerd Lakes', latitude: 46.6738, longitude: -94.1130 },
    { slug: 'breezy-point',        name: 'Breezy Point',        state: 'MN', region: 'Brainerd Lakes', latitude: 46.5808, longitude: -94.2186 },
    { slug: 'crosby',              name: 'Crosby',              state: 'MN', region: 'Brainerd Lakes', latitude: 46.4822, longitude: -93.9572 },
    { slug: 'aitkin',              name: 'Aitkin',              state: 'MN', region: 'Brainerd Lakes', latitude: 46.5327, longitude: -93.7099 },
    { slug: 'pine-river',          name: 'Pine River',          state: 'MN', region: 'Brainerd Lakes', latitude: 46.7222, longitude: -94.4011 },
    { slug: 'hackensack',          name: 'Hackensack',          state: 'MN', region: 'Brainerd Lakes', latitude: 46.9297, longitude: -94.5219 },
    { slug: 'walker',              name: 'Walker',              state: 'MN', region: 'Brainerd Lakes', latitude: 47.1006, longitude: -94.5872 },
    { slug: 'cass-lake',           name: 'Cass Lake',           state: 'MN', region: 'Brainerd Lakes', latitude: 47.3789, longitude: -94.6083 },

    // ── Alexandria Lakes ─────────────────────────────────────────────────────
    { slug: 'alexandria',          name: 'Alexandria',          state: 'MN', region: 'Alexandria Lakes', latitude: 45.8852, longitude: -95.3775 },
    { slug: 'osakis',              name: 'Osakis',              state: 'MN', region: 'Alexandria Lakes', latitude: 45.8677, longitude: -95.1511 },
    { slug: 'glenwood',            name: 'Glenwood',            state: 'MN', region: 'Alexandria Lakes', latitude: 45.6494, longitude: -95.3908 },
    { slug: 'parkers-prairie',     name: 'Parkers Prairie',     state: 'MN', region: 'Alexandria Lakes', latitude: 46.1527, longitude: -95.3292 },

    // ── Lakes Country ────────────────────────────────────────────────────────
    { slug: 'detroit-lakes',       name: 'Detroit Lakes',       state: 'MN', region: 'Lakes Country', latitude: 46.8169, longitude: -95.8453 },
    { slug: 'perham',              name: 'Perham',              state: 'MN', region: 'Lakes Country', latitude: 46.5950, longitude: -95.5728 },
    { slug: 'frazee',              name: 'Frazee',              state: 'MN', region: 'Lakes Country', latitude: 46.7280, longitude: -95.7000 },
    { slug: 'vergas',              name: 'Vergas',              state: 'MN', region: 'Lakes Country', latitude: 46.6617, longitude: -95.8072 },
    { slug: 'pelican-rapids',      name: 'Pelican Rapids',      state: 'MN', region: 'Lakes Country', latitude: 46.5713, longitude: -96.0833 },
    { slug: 'battle-lake',         name: 'Battle Lake',         state: 'MN', region: 'Lakes Country', latitude: 46.2813, longitude: -95.7147 },
    { slug: 'ottertail',           name: 'Ottertail',           state: 'MN', region: 'Lakes Country', latitude: 46.4172, longitude: -95.5567 },
    { slug: 'new-york-mills',      name: 'New York Mills',      state: 'MN', region: 'Lakes Country', latitude: 46.5180, longitude: -95.3764 },
    { slug: 'menahga',             name: 'Menahga',             state: 'MN', region: 'Lakes Country', latitude: 46.7547, longitude: -95.0975 },
    { slug: 'wadena',              name: 'Wadena',              state: 'MN', region: 'Lakes Country', latitude: 46.4424, longitude: -95.1364 },
    { slug: 'park-rapids',         name: 'Park Rapids',         state: 'MN', region: 'Lakes Country', latitude: 46.9222, longitude: -95.0586 },

    // ── Northern / West Central MN ──────────────────────────────────────────
    { slug: 'bemidji',             name: 'Bemidji',             state: 'MN', region: 'Northern MN',   latitude: 47.4716, longitude: -94.8827 },
    { slug: 'fergus-falls',        name: 'Fergus Falls',        state: 'MN', region: 'West Central MN', latitude: 46.2830, longitude: -96.0776 },

    // ── Fargo-Moorhead ───────────────────────────────────────────────────────
    { slug: 'moorhead',            name: 'Moorhead',            state: 'MN', region: 'Fargo-Moorhead', latitude: 46.8736, longitude: -96.7678 },
    { slug: 'dilworth',            name: 'Dilworth',            state: 'MN', region: 'Fargo-Moorhead', latitude: 46.8761, longitude: -96.7025 },
    { slug: 'hawley',              name: 'Hawley',              state: 'MN', region: 'Fargo-Moorhead', latitude: 46.8811, longitude: -96.3164 },
    { slug: 'glyndon',             name: 'Glyndon',             state: 'MN', region: 'Fargo-Moorhead', latitude: 46.8744, longitude: -96.5775 },
    { slug: 'barnesville',         name: 'Barnesville',         state: 'MN', region: 'Fargo-Moorhead', latitude: 46.6513, longitude: -96.4194 },
    { slug: 'breckenridge',        name: 'Breckenridge',        state: 'MN', region: 'West Central MN', latitude: 46.2644, longitude: -96.5853 },

    // ── Red River Valley ─────────────────────────────────────────────────────
    { slug: 'crookston',           name: 'Crookston',           state: 'MN', region: 'Red River Valley', latitude: 47.7744, longitude: -96.6081 },
    { slug: 'east-grand-forks',    name: 'East Grand Forks',    state: 'MN', region: 'Red River Valley', latitude: 47.9295, longitude: -97.0236 },
    { slug: 'thief-river-falls',   name: 'Thief River Falls',   state: 'MN', region: 'Red River Valley', latitude: 48.1191, longitude: -96.1811 },
    { slug: 'warren',              name: 'Warren',              state: 'MN', region: 'Red River Valley', latitude: 48.1969, longitude: -96.7708 },

    // ── Far North MN ─────────────────────────────────────────────────────────
    { slug: 'roseau',              name: 'Roseau',              state: 'MN', region: 'Northern MN', latitude: 48.8461, longitude: -95.7625 },
    { slug: 'baudette',            name: 'Baudette',            state: 'MN', region: 'Northern MN', latitude: 48.7122, longitude: -94.5994 },
    { slug: 'international-falls', name: 'International Falls', state: 'MN', region: 'Northern MN', latitude: 48.6011, longitude: -93.4100 },

    // ── Iron Range ───────────────────────────────────────────────────────────
    { slug: 'grand-rapids',        name: 'Grand Rapids',        state: 'MN', region: 'Iron Range', latitude: 47.2372, longitude: -93.5302 },
    { slug: 'hibbing',              name: 'Hibbing',            state: 'MN', region: 'Iron Range', latitude: 47.4272, longitude: -92.9377 },
    { slug: 'virginia',             name: 'Virginia',           state: 'MN', region: 'Iron Range', latitude: 47.5233, longitude: -92.5366 },
    { slug: 'eveleth',              name: 'Eveleth',            state: 'MN', region: 'Iron Range', latitude: 47.4625, longitude: -92.5402 },
    { slug: 'mountain-iron',        name: 'Mountain Iron',      state: 'MN', region: 'Iron Range', latitude: 47.5322, longitude: -92.6247 },
    { slug: 'chisholm',             name: 'Chisholm',           state: 'MN', region: 'Iron Range', latitude: 47.4889, longitude: -92.8838 },
    { slug: 'ely',                  name: 'Ely',                state: 'MN', region: 'Iron Range', latitude: 47.9033, longitude: -91.8671 },

    // ── Duluth Area ──────────────────────────────────────────────────────────
    { slug: 'duluth',               name: 'Duluth',             state: 'MN', region: 'Duluth Area', latitude: 46.7867, longitude: -92.1005 },
    { slug: 'hermantown',           name: 'Hermantown',         state: 'MN', region: 'Duluth Area', latitude: 46.8008, longitude: -92.2383 },
    { slug: 'proctor',              name: 'Proctor',            state: 'MN', region: 'Duluth Area', latitude: 46.7472, longitude: -92.2254 },
    { slug: 'cloquet',              name: 'Cloquet',            state: 'MN', region: 'Duluth Area', latitude: 46.7216, longitude: -92.4594 },
    { slug: 'two-harbors',          name: 'Two Harbors',        state: 'MN', region: 'Duluth Area', latitude: 47.0227, longitude: -91.6706 },

    // ── Southeast MN ─────────────────────────────────────────────────────────
    { slug: 'rochester',            name: 'Rochester',          state: 'MN', region: 'Southeast MN', latitude: 44.0121, longitude: -92.4802 },
    { slug: 'winona',               name: 'Winona',             state: 'MN', region: 'Southeast MN', latitude: 44.0499, longitude: -91.6393 },
    { slug: 'red-wing',             name: 'Red Wing',           state: 'MN', region: 'Southeast MN', latitude: 44.5625, longitude: -92.5335 },
    { slug: 'austin',               name: 'Austin',             state: 'MN', region: 'Southeast MN', latitude: 43.6666, longitude: -92.9746 },
    { slug: 'albert-lea',           name: 'Albert Lea',         state: 'MN', region: 'Southeast MN', latitude: 43.6481, longitude: -93.3683 },
    { slug: 'owatonna',             name: 'Owatonna',           state: 'MN', region: 'Southeast MN', latitude: 44.0834, longitude: -93.2260 },
    { slug: 'faribault',            name: 'Faribault',          state: 'MN', region: 'Southeast MN', latitude: 44.2952, longitude: -93.2690 },
    { slug: 'northfield',           name: 'Northfield',         state: 'MN', region: 'Southeast MN', latitude: 44.4580, longitude: -93.1616 },
    { slug: 'cannon-falls',         name: 'Cannon Falls',       state: 'MN', region: 'Southeast MN', latitude: 44.5069, longitude: -92.9052 },
    { slug: 'lake-city',            name: 'Lake City',          state: 'MN', region: 'Southeast MN', latitude: 44.4500, longitude: -92.2683 },
    { slug: 'wabasha',              name: 'Wabasha',            state: 'MN', region: 'Southeast MN', latitude: 44.3836, longitude: -92.0332 },
    { slug: 'zumbrota',             name: 'Zumbrota',           state: 'MN', region: 'Southeast MN', latitude: 44.2944, longitude: -92.6694 },
    { slug: 'kasson',               name: 'Kasson',             state: 'MN', region: 'Southeast MN', latitude: 44.0308, longitude: -92.7510 },
    { slug: 'stewartville',         name: 'Stewartville',       state: 'MN', region: 'Southeast MN', latitude: 43.8555, longitude: -92.4896 },

    // ── South Central MN ─────────────────────────────────────────────────────
    { slug: 'mankato',              name: 'Mankato',            state: 'MN', region: 'South Central MN', latitude: 44.1636, longitude: -93.9994 },
    { slug: 'north-mankato',        name: 'North Mankato',      state: 'MN', region: 'South Central MN', latitude: 44.1733, longitude: -94.0357 },
    { slug: 'new-ulm',              name: 'New Ulm',            state: 'MN', region: 'South Central MN', latitude: 44.3124, longitude: -94.4600 },
    { slug: 'st-peter',             name: 'Saint Peter',        state: 'MN', region: 'South Central MN', latitude: 44.3236, longitude: -93.9577 },
    { slug: 'le-sueur',             name: 'Le Sueur',           state: 'MN', region: 'South Central MN', latitude: 44.4619, longitude: -93.9122 },

    // ── Southwest MN ─────────────────────────────────────────────────────────
    { slug: 'marshall',             name: 'Marshall',           state: 'MN', region: 'Southwest MN', latitude: 44.4469, longitude: -95.7886 },
    { slug: 'worthington',          name: 'Worthington',        state: 'MN', region: 'Southwest MN', latitude: 43.6197, longitude: -95.5964 },
    { slug: 'fairmont',             name: 'Fairmont',           state: 'MN', region: 'Southwest MN', latitude: 43.6521, longitude: -94.4611 },
    { slug: 'windom',               name: 'Windom',             state: 'MN', region: 'Southwest MN', latitude: 43.8694, longitude: -95.1169 },
    { slug: 'luverne',              name: 'Luverne',            state: 'MN', region: 'Southwest MN', latitude: 43.6541, longitude: -96.2128 },
    { slug: 'pipestone',            name: 'Pipestone',          state: 'MN', region: 'Southwest MN', latitude: 44.0005, longitude: -96.3175 },
    { slug: 'redwood-falls',        name: 'Redwood Falls',      state: 'MN', region: 'Southwest MN', latitude: 44.5394, longitude: -95.1169 },
    { slug: 'granite-falls',        name: 'Granite Falls',      state: 'MN', region: 'Southwest MN', latitude: 44.8097, longitude: -95.5453 },

    // ── West Central MN ──────────────────────────────────────────────────────
    { slug: 'willmar',              name: 'Willmar',            state: 'MN', region: 'West Central MN', latitude: 45.1219, longitude: -95.0433 },
    { slug: 'hutchinson',           name: 'Hutchinson',         state: 'MN', region: 'West Central MN', latitude: 44.8880, longitude: -94.3694 },
    { slug: 'litchfield',           name: 'Litchfield',         state: 'MN', region: 'West Central MN', latitude: 45.1275, longitude: -94.5280 },
    { slug: 'dassel',               name: 'Dassel',             state: 'MN', region: 'West Central MN', latitude: 45.0830, longitude: -94.3080 },
    { slug: 'cokato',               name: 'Cokato',             state: 'MN', region: 'West Central MN', latitude: 45.0764, longitude: -94.1903 },
    { slug: 'montevideo',           name: 'Montevideo',         state: 'MN', region: 'West Central MN', latitude: 44.9425, longitude: -95.7236 },
    { slug: 'benson',               name: 'Benson',             state: 'MN', region: 'West Central MN', latitude: 45.3152, longitude: -95.5994 },
    { slug: 'morris',               name: 'Morris',             state: 'MN', region: 'West Central MN', latitude: 45.5858, longitude: -95.9139 },

    // ── North Dakota ─────────────────────────────────────────────────────────
    { slug: 'fargo',                name: 'Fargo',              state: 'ND', region: 'Fargo-Moorhead',  latitude: 46.8772, longitude: -96.7898 },
    { slug: 'west-fargo',           name: 'West Fargo',         state: 'ND', region: 'Fargo-Moorhead',  latitude: 46.8750, longitude: -96.9000 },
    { slug: 'horace',               name: 'Horace',             state: 'ND', region: 'Fargo-Moorhead',  latitude: 46.7492, longitude: -96.9083 },
    { slug: 'mapleton',             name: 'Mapleton',           state: 'ND', region: 'Fargo-Moorhead',  latitude: 46.8961, longitude: -97.0514 },
    { slug: 'grand-forks',          name: 'Grand Forks',        state: 'ND', region: 'Red River Valley', latitude: 47.9253, longitude: -97.0329 },
    { slug: 'wahpeton',             name: 'Wahpeton',           state: 'ND', region: 'Red River Valley', latitude: 46.2653, longitude: -96.6059 },
    { slug: 'bismarck',             name: 'Bismarck',           state: 'ND', region: 'Central ND',       latitude: 46.8083, longitude: -100.7837 },
    { slug: 'mandan',               name: 'Mandan',             state: 'ND', region: 'Central ND',       latitude: 46.8267, longitude: -100.8896 },
    { slug: 'jamestown',            name: 'Jamestown',          state: 'ND', region: 'Central ND',       latitude: 46.9105, longitude: -98.7084 },
    { slug: 'valley-city',          name: 'Valley City',        state: 'ND', region: 'Central ND',       latitude: 46.9233, longitude: -98.0032 },
    { slug: 'devils-lake',          name: 'Devils Lake',        state: 'ND', region: 'Central ND',       latitude: 48.1128, longitude: -98.8650 },
    { slug: 'minot',                name: 'Minot',              state: 'ND', region: 'Western ND',       latitude: 48.2330, longitude: -101.2957 },
    { slug: 'dickinson',            name: 'Dickinson',          state: 'ND', region: 'Western ND',       latitude: 46.8792, longitude: -102.7896 },

    // ── Western Wisconsin ────────────────────────────────────────────────────
    { slug: 'superior',             name: 'Superior',           state: 'WI', region: 'Northern WI', latitude: 46.7208, longitude: -92.1041 },
    { slug: 'hudson',               name: 'Hudson',             state: 'WI', region: 'Western WI',  latitude: 44.9747, longitude: -92.7569 },
    { slug: 'river-falls',          name: 'River Falls',        state: 'WI', region: 'Western WI',  latitude: 44.8613, longitude: -92.6237 },
    { slug: 'new-richmond',         name: 'New Richmond',       state: 'WI', region: 'Western WI',  latitude: 45.1233, longitude: -92.5366 },
    { slug: 'hayward',              name: 'Hayward',            state: 'WI', region: 'Northern WI', latitude: 46.0130, longitude: -91.4846 },
    { slug: 'spooner',              name: 'Spooner',            state: 'WI', region: 'Northern WI', latitude: 45.8222, longitude: -91.8893 },
    { slug: 'rice-lake',            name: 'Rice Lake',          state: 'WI', region: 'Northern WI', latitude: 45.5061, longitude: -91.7357 },
    { slug: 'ashland',              name: 'Ashland',            state: 'WI', region: 'Northern WI', latitude: 46.5924, longitude: -90.8838 },
];
